service: nestjs-sls-dynamo-lambda

plugins:
  - serverless-layers
  - serverless-offline
  - serverless-domain-manager

custom:
  config:
    dev:
      baseDomain: 'backend-api.dev.levena.link'
  defaultStage: dev
  profiles:
    dev: default
    prod: prod
  serverless-layers:
    layersDeploymentBucket: nestjs-sls-dynamo-lambda-graphql
  customDomain:
    domainName: ${self:custom.config.${self:provider.stage}.baseDomain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  # serverless-offline:
  #   httpPort: 3002

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  environment:
    SERVERLESS_STAGE: ${self:provider.stage}

package:
  individually: true
  include:
    - dist/**
  exclude:
    - '**'

functions:
  index:
    handler: dist/handler.handler
    events:
      - http:
          path: '/'
          method: any
      - http:
          path: '{proxy+}'
          method: any