service: nestjs-sls-dynamo-lambda
plugins:
  - serverless-layers
  - serverless-offline

custom:
  defaultStage: dev
  profiles:
    dev: default
    prod: prod
  serverless-layer:
    layerDeployermentBucket: nestjs-sls-dynamo-lambda
  # serverless-offline:
  #   httpPort: 3002

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  # stage: ${opt.stage, 'dev'}
  # profile: ${self:custom.profiles.${self:provider.stage}}
  # environment:
  #   SERVERLESS_STAGE: ${self:provider.stage}

package:
  individually: true
  include:
    - dist/**
  exclude:
    - '**'

functions:
  index:
    handler: dist/handler.handler
    events:
      - http:
          path: '/'
          method: any
      - http:
          path: '{proxy+}'
          method: any